spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?characterEncoding=utf-8&serverTimezone=UTC
    #hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
    username: root
   # password: venustech.tsoc.db.ROOT
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
# resources:
#    static-locations: classpath:/static/
#设置上传文件的大小，单个和总和
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

